onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /datapath_tb/dut/Clk
add wave -noupdate /datapath_tb/dut/Reset
add wave -noupdate -divider {NextPC Stage}
add wave -noupdate /datapath_tb/dut/PC1JumpN
add wave -noupdate /datapath_tb/dut/PC2JumpN
add wave -noupdate /datapath_tb/dut/PCCBN
add wave -noupdate /datapath_tb/dut/PCCNBN
add wave -noupdate /datapath_tb/dut/PCJN
add wave -noupdate /datapath_tb/dut/PCPN
add wave -noupdate /datapath_tb/dut/PCPredict1N
add wave -noupdate /datapath_tb/dut/PCPredict2N
add wave -noupdate -divider {Fetch Stage}
add wave -noupdate /datapath_tb/dut/Prediction1F
add wave -noupdate /datapath_tb/dut/Prediction2F
add wave -noupdate /datapath_tb/dut/StallF
add wave -noupdate /datapath_tb/dut/Instr1F
add wave -noupdate /datapath_tb/dut/Instr2F
add wave -noupdate /datapath_tb/dut/PC1F
add wave -noupdate /datapath_tb/dut/PC2F
add wave -noupdate /datapath_tb/dut/PC1Plus8F
add wave -noupdate -divider {Decode Stage}
add wave -noupdate /datapath_tb/dut/ALUSrc1D
add wave -noupdate /datapath_tb/dut/ALUSrc2D
add wave -noupdate /datapath_tb/dut/Branch1D
add wave -noupdate /datapath_tb/dut/Branch2D
add wave -noupdate /datapath_tb/dut/Flush1D
add wave -noupdate /datapath_tb/dut/Flush2D
add wave -noupdate /datapath_tb/dut/Jump1D
add wave -noupdate /datapath_tb/dut/Jump2D
add wave -noupdate /datapath_tb/dut/MemRead1D
add wave -noupdate /datapath_tb/dut/MemRead2D
add wave -noupdate /datapath_tb/dut/MemtoReg1D
add wave -noupdate /datapath_tb/dut/MemtoReg2D
add wave -noupdate /datapath_tb/dut/MemWrite1D
add wave -noupdate /datapath_tb/dut/MemWrite2D
add wave -noupdate /datapath_tb/dut/Prediction1D
add wave -noupdate /datapath_tb/dut/Prediction2D
add wave -noupdate /datapath_tb/dut/RegDst1D
add wave -noupdate /datapath_tb/dut/RegDst2D
add wave -noupdate /datapath_tb/dut/RegWrite1D
add wave -noupdate /datapath_tb/dut/RegWrite2D
add wave -noupdate /datapath_tb/dut/SeZe1D
add wave -noupdate /datapath_tb/dut/SeZe2D
add wave -noupdate /datapath_tb/dut/Stall1D
add wave -noupdate /datapath_tb/dut/Stall2D
add wave -noupdate /datapath_tb/dut/ALUControl1D
add wave -noupdate /datapath_tb/dut/ALUControl2D
add wave -noupdate /datapath_tb/dut/Rd1D
add wave -noupdate /datapath_tb/dut/Rd2D
add wave -noupdate /datapath_tb/dut/Rs1D
add wave -noupdate /datapath_tb/dut/Rs2D
add wave -noupdate /datapath_tb/dut/Rt1D
add wave -noupdate /datapath_tb/dut/Rt2D
add wave -noupdate /datapath_tb/dut/ExtImm1D
add wave -noupdate /datapath_tb/dut/ExtImm2D
add wave -noupdate /datapath_tb/dut/Instr1D
add wave -noupdate /datapath_tb/dut/Instr2D
add wave -noupdate /datapath_tb/dut/PC1D
add wave -noupdate /datapath_tb/dut/PC2D
add wave -noupdate /datapath_tb/dut/PC1Plus4D
add wave -noupdate /datapath_tb/dut/PC2Plus4D
add wave -noupdate /datapath_tb/dut/PCBranch1D
add wave -noupdate /datapath_tb/dut/PCBranch2D
add wave -noupdate /datapath_tb/dut/RD11D
add wave -noupdate /datapath_tb/dut/RD12D
add wave -noupdate /datapath_tb/dut/RD21D
add wave -noupdate /datapath_tb/dut/RD22D
add wave -noupdate /datapath_tb/dut/SignExt1D
add wave -noupdate /datapath_tb/dut/SignExt2D
add wave -noupdate /datapath_tb/dut/ZeroExt1D
add wave -noupdate /datapath_tb/dut/ZeroExt2D
add wave -noupdate -divider {Execute Stage}
add wave -noupdate /datapath_tb/dut/ALUSrc1E
add wave -noupdate /datapath_tb/dut/ALUSrc2E
add wave -noupdate /datapath_tb/dut/Branch1E
add wave -noupdate /datapath_tb/dut/Branch2E
add wave -noupdate /datapath_tb/dut/BufferWrite1E
add wave -noupdate /datapath_tb/dut/BufferWrite2E
add wave -noupdate /datapath_tb/dut/Correction1E
add wave -noupdate /datapath_tb/dut/Correction2E
add wave -noupdate /datapath_tb/dut/EqNe1E
add wave -noupdate /datapath_tb/dut/EqNe2E
add wave -noupdate /datapath_tb/dut/Flush1E
add wave -noupdate /datapath_tb/dut/Flush2E
add wave -noupdate /datapath_tb/dut/MemRead1E
add wave -noupdate /datapath_tb/dut/MemRead2E
add wave -noupdate /datapath_tb/dut/MemtoReg1E
add wave -noupdate /datapath_tb/dut/MemtoReg2E
add wave -noupdate /datapath_tb/dut/MemWrite1E
add wave -noupdate /datapath_tb/dut/MemWrite2E
add wave -noupdate /datapath_tb/dut/PCSrc1E
add wave -noupdate /datapath_tb/dut/PCSrc2E
add wave -noupdate /datapath_tb/dut/Prediction1E
add wave -noupdate /datapath_tb/dut/Prediction2E
add wave -noupdate /datapath_tb/dut/RegDst1E
add wave -noupdate /datapath_tb/dut/RegDst2E
add wave -noupdate /datapath_tb/dut/RegWrite1E
add wave -noupdate /datapath_tb/dut/RegWrite2E
add wave -noupdate /datapath_tb/dut/Stall1E
add wave -noupdate /datapath_tb/dut/Stall2E
add wave -noupdate /datapath_tb/dut/Taken1E
add wave -noupdate /datapath_tb/dut/Taken2E
add wave -noupdate /datapath_tb/dut/Zero1E
add wave -noupdate /datapath_tb/dut/Zero2E
add wave -noupdate /datapath_tb/dut/ForwardA1E
add wave -noupdate /datapath_tb/dut/ForwardA2E
add wave -noupdate /datapath_tb/dut/ForwardB1E
add wave -noupdate /datapath_tb/dut/ForwardB2E
add wave -noupdate /datapath_tb/dut/ALUControl1E
add wave -noupdate /datapath_tb/dut/ALUControl2E
add wave -noupdate /datapath_tb/dut/Rd1E
add wave -noupdate /datapath_tb/dut/Rd2E
add wave -noupdate /datapath_tb/dut/Rs1E
add wave -noupdate /datapath_tb/dut/Rs2E
add wave -noupdate /datapath_tb/dut/Rt1E
add wave -noupdate /datapath_tb/dut/Rt2E
add wave -noupdate /datapath_tb/dut/WriteReg1E
add wave -noupdate /datapath_tb/dut/WriteReg2E
add wave -noupdate /datapath_tb/dut/ALUOut1E
add wave -noupdate /datapath_tb/dut/ALUOut2E
add wave -noupdate /datapath_tb/dut/ExtImm1E
add wave -noupdate /datapath_tb/dut/ExtImm2E
add wave -noupdate /datapath_tb/dut/PC1E
add wave -noupdate /datapath_tb/dut/PC2E
add wave -noupdate /datapath_tb/dut/PC1Plus4E
add wave -noupdate /datapath_tb/dut/PC2Plus4E
add wave -noupdate /datapath_tb/dut/PCBranch1E
add wave -noupdate /datapath_tb/dut/PCBranch2E
add wave -noupdate /datapath_tb/dut/RD11E
add wave -noupdate /datapath_tb/dut/RD12E
add wave -noupdate /datapath_tb/dut/RD21E
add wave -noupdate /datapath_tb/dut/RD22E
add wave -noupdate /datapath_tb/dut/SrcA1E
add wave -noupdate -radix hexadecimal /datapath_tb/dut/SrcA2E
add wave -noupdate /datapath_tb/dut/SrcB1E
add wave -noupdate /datapath_tb/dut/SrcB2E
add wave -noupdate /datapath_tb/dut/WriteData1E
add wave -noupdate /datapath_tb/dut/WriteData2E
add wave -noupdate -divider {Memory Stage}
add wave -noupdate /datapath_tb/dut/Flush1M
add wave -noupdate /datapath_tb/dut/Flush2M
add wave -noupdate /datapath_tb/dut/MemRead1M
add wave -noupdate /datapath_tb/dut/MemRead2M
add wave -noupdate /datapath_tb/dut/MemtoReg1M
add wave -noupdate /datapath_tb/dut/MemtoReg2M
add wave -noupdate /datapath_tb/dut/MemWrite1M
add wave -noupdate /datapath_tb/dut/MemWrite2M
add wave -noupdate /datapath_tb/dut/RegWrite1M
add wave -noupdate /datapath_tb/dut/RegWrite2M
add wave -noupdate /datapath_tb/dut/Stall1M
add wave -noupdate /datapath_tb/dut/Stall2M
add wave -noupdate /datapath_tb/dut/WriteReg1M
add wave -noupdate /datapath_tb/dut/WriteReg2M
add wave -noupdate /datapath_tb/dut/ALUOut1M
add wave -noupdate /datapath_tb/dut/ALUOut2M
add wave -noupdate /datapath_tb/dut/ReadData1M
add wave -noupdate /datapath_tb/dut/ReadData2M
add wave -noupdate /datapath_tb/dut/WriteData1M
add wave -noupdate /datapath_tb/dut/WriteData2M
add wave -noupdate -divider {Writeback Stage}
add wave -noupdate /datapath_tb/dut/MemtoReg1W
add wave -noupdate /datapath_tb/dut/MemtoReg2W
add wave -noupdate /datapath_tb/dut/RegWrite1W
add wave -noupdate /datapath_tb/dut/RegWrite2W
add wave -noupdate /datapath_tb/dut/StallW
add wave -noupdate /datapath_tb/dut/WriteReg1W
add wave -noupdate /datapath_tb/dut/WriteReg2W
add wave -noupdate /datapath_tb/dut/ALUOut1W
add wave -noupdate /datapath_tb/dut/ALUOut2W
add wave -noupdate /datapath_tb/dut/ReadData1W
add wave -noupdate /datapath_tb/dut/ReadData2W
add wave -noupdate /datapath_tb/dut/Result1W
add wave -noupdate /datapath_tb/dut/Result2W
add wave -noupdate -divider {Branch Target Buffer}
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WE1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WE2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/US1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/US2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/T1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/T2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/RA1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/RA2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WA1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WA2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WD1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/WD2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/P1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/P2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/RD1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/RD2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/read_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/read_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/write_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/write_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/bht_read_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/bht_read_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/bht_write_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/bht_write_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/pht_read_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/pht_read_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/pht_write_index1
add wave -noupdate /datapath_tb/dut/branch_target_buffer/pht_write_index2
add wave -noupdate /datapath_tb/dut/branch_target_buffer/branch_history_table
add wave -noupdate /datapath_tb/dut/branch_target_buffer/predicted_pc
add wave -noupdate /datapath_tb/dut/branch_target_buffer/pattern_history_table
add wave -noupdate -divider {Register File}
add wave -noupdate -expand /datapath_tb/dut/register_file/regfile
add wave -noupdate -divider {Data Memory}
add wave -noupdate /datapath_tb/dut/data_mem/RAM
add wave -noupdate -divider {Hazard Unit}
add wave -noupdate /datapath_tb/dut/haz_unit/ALUSrc1D
add wave -noupdate /datapath_tb/dut/haz_unit/ALUSrc2D
add wave -noupdate /datapath_tb/dut/haz_unit/Branch1D
add wave -noupdate /datapath_tb/dut/haz_unit/Jump1D
add wave -noupdate /datapath_tb/dut/haz_unit/Jump2D
add wave -noupdate /datapath_tb/dut/haz_unit/MemtoReg1E
add wave -noupdate /datapath_tb/dut/haz_unit/MemtoReg2E
add wave -noupdate /datapath_tb/dut/haz_unit/MemWrite1E
add wave -noupdate /datapath_tb/dut/haz_unit/MemWrite2D
add wave -noupdate /datapath_tb/dut/haz_unit/Prediction1E
add wave -noupdate /datapath_tb/dut/haz_unit/Prediction2E
add wave -noupdate /datapath_tb/dut/haz_unit/RegWrite1M
add wave -noupdate /datapath_tb/dut/haz_unit/RegWrite1W
add wave -noupdate /datapath_tb/dut/haz_unit/RegWrite2M
add wave -noupdate /datapath_tb/dut/haz_unit/RegWrite2W
add wave -noupdate /datapath_tb/dut/haz_unit/Taken1E
add wave -noupdate /datapath_tb/dut/haz_unit/Taken2E
add wave -noupdate /datapath_tb/dut/haz_unit/Rd1D
add wave -noupdate /datapath_tb/dut/haz_unit/Rs1D
add wave -noupdate /datapath_tb/dut/haz_unit/Rs2D
add wave -noupdate /datapath_tb/dut/haz_unit/Rs1E
add wave -noupdate /datapath_tb/dut/haz_unit/Rs2E
add wave -noupdate /datapath_tb/dut/haz_unit/Rt1D
add wave -noupdate /datapath_tb/dut/haz_unit/Rt2D
add wave -noupdate /datapath_tb/dut/haz_unit/Rt1E
add wave -noupdate /datapath_tb/dut/haz_unit/Rt2E
add wave -noupdate /datapath_tb/dut/haz_unit/WriteReg1M
add wave -noupdate /datapath_tb/dut/haz_unit/WriteReg1W
add wave -noupdate /datapath_tb/dut/haz_unit/WriteReg2M
add wave -noupdate /datapath_tb/dut/haz_unit/WriteReg2W
add wave -noupdate /datapath_tb/dut/haz_unit/ALUOut1E
add wave -noupdate /datapath_tb/dut/haz_unit/ALUOut2E
add wave -noupdate /datapath_tb/dut/haz_unit/Flush1D
add wave -noupdate /datapath_tb/dut/haz_unit/Flush2D
add wave -noupdate /datapath_tb/dut/haz_unit/Flush1E
add wave -noupdate /datapath_tb/dut/haz_unit/Flush2E
add wave -noupdate /datapath_tb/dut/haz_unit/Flush1M
add wave -noupdate /datapath_tb/dut/haz_unit/Flush2M
add wave -noupdate /datapath_tb/dut/haz_unit/StallF
add wave -noupdate /datapath_tb/dut/haz_unit/Stall1D
add wave -noupdate /datapath_tb/dut/haz_unit/Stall2D
add wave -noupdate /datapath_tb/dut/haz_unit/Stall2E
add wave -noupdate /datapath_tb/dut/haz_unit/ForwardA1E
add wave -noupdate /datapath_tb/dut/haz_unit/ForwardA2E
add wave -noupdate /datapath_tb/dut/haz_unit/ForwardB1E
add wave -noupdate /datapath_tb/dut/haz_unit/ForwardB2E
add wave -noupdate /datapath_tb/dut/haz_unit/lwstall
add wave -noupdate /datapath_tb/dut/haz_unit/memstall
add wave -noupdate /datapath_tb/dut/haz_unit/samecyclestall
add wave -noupdate /datapath_tb/dut/haz_unit/wrongprediction1
add wave -noupdate /datapath_tb/dut/haz_unit/wrongprediction2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {56 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 352
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {112 ns}
